api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.views import UserViewSet, CarViewSet, GroupViewSet, SolicitationViewSet, PassengerViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'cars', CarViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'solicitations', SolicitationViewSet)
router.register(r'passengers', PassengerViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

ifcarros/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.views import get_swagger_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
# from django.conf.urls.i18n import i18n_patterns

# schema_view = get_schema_view(title='MINHA API')
schema_view = get_swagger_view(title='IF Carros')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls')),
    url(r'^conta/', include('django.contrib.auth.urls')),
    url(r'^swagger', schema_view),
    url(r'^web/', include('web.urls')),
]

# urlpatterns += ([
#     path("", include('base.urls'))
# ]) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from django.urls import path
from django.contrib import admin
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordChangeDoneView, PasswordResetConfirmView
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
#from api.views import UserViewSet, CarViewSet, GroupViewSet, SolicitationViewSet, PassengerViewSet

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'cars', CarViewSet)
# router.register(r'groups', GroupViewSet)
# router.register(r'solicitations', SolicitationViewSet)
# router.register(r'passengers', PassengerViewSet)
app_name = 'web'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(redirect_authenticated_user=True), {'template_name': 'registration/login.html'}, name='login'),
    url(r'^password_reset/$', PasswordResetView.as_view(), {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', TemplateView.as_view(template_name='web/home/home.html'), name='home'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    
]

web/templates/web/_layouts/base.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <!-- Title -->
    <title>
      {% block title %}ADS | IFC{% endblock %}
    </title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'web/img/favicon.ico' %}" type="image/png">

    <!-- Arquivos CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'web/css/main.css' %}">

    <!-- Bloco de Estilos -->
    {% block styles %}{% endblock %}
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-1">
        <a class="navbar-brand" href="{% url 'web:home' %}">
          <img src="{% static 'web/img/favicon.png' %}" height='45px'>
        </a>
        <button class="navbar-toggler" type="button" 
            data-toggle="collapse" data-target="#conteudo-navbar" 
            aria-controls="conteudo-navbar" aria-expanded="false" 
            aria-label="Ativar navegação">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="conteudo-navbar">
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'web:login' %}">
                      Login
                    </a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="/media/{{ request.user.profile.avatar }}" height="35px" class="rounded">
                    <!-- {user.username|capfirst} -->
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'web:profile' %}">Perfil</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'web:logout' %}">
                      Logout
                    </a>
                  </div>
                </li>
              {% endif %}
            </ul>
        </div>
    </nav>
      
    <!-- Bloco de conteúdo -->
    {% block conteudo %}{% endblock %}

    <!-- Arquivos necessários para o Bootstrap -->
    <!-- <script src="{% static 'website/js/jquery.min.js' %}"></script>
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script> -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Bloco de scripts -->
    {% block scripts %}{% endblock %}

    <!-- Scripts.js -->
    <script src="{% static 'web/js/main.js' %}"></script>
  </body>
</html>